/**
 * Retry a single topic candidate (including a starred repo — `kind: "star"`)
 * that qualified for auto-generation but never got its article — the
 * backend half of the edit page's per-candidate "failed, retry" card.
 * Sibling of `.../topic-candidates/[candidateId]/toggle/route.ts`, same
 * shape as `.../articles/[articleId]/regenerate/route.ts`.
 */

import type { NextRequest } from "next/server";
import { regenerateTopicCandidateArticle } from "@/lib/generation";
import { AI_PROVIDER_NOT_CONFIGURED_MESSAGE, resolveAiModel } from "@/lib/ai/provider";
import { describeError, flashRedirect, type FlashMessage } from "@/lib/flash";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ editionId: string; candidateId: string }> },
) {
  const { editionId, candidateId } = await params;
  const eId = Number(editionId);

  const aiModel = await resolveAiModel();
  if (!aiModel) {
    return flashRedirect(request, `/admin/editions/${eId}/edit#github-insights`, [
      { type: "error", text: AI_PROVIDER_NOT_CONFIGURED_MESSAGE },
    ]);
  }

  let message: FlashMessage;
  try {
    await regenerateTopicCandidateArticle(eId, candidateId, aiModel);
    message = { type: "success", text: "Topic candidate regenerated by AI." };
  } catch (error) {
    message = { type: "error", text: `AI regeneration failed: ${describeError(error)}` };
  }

  return flashRedirect(request, `/admin/editions/${eId}/edit#github-insights`, [message]);
}
