/**
 * Retry a single chronicle section that had activity but never got a
 * written article (bad AI provider, transient failure, etc.) — the backend
 * half of the edit page's per-section "failed, retry" card. Same shape as
 * `.../articles/[articleId]/regenerate/route.ts`, just targeting a chronicle
 * category instead of an existing `Article`.
 */

import type { NextRequest } from "next/server";
import { CATEGORIES, type ChronicleCategory } from "@/mastra/workflows";
import { regenerateChronicleSection } from "@/lib/generation";
import { AI_PROVIDER_NOT_CONFIGURED_MESSAGE, resolveAiModel } from "@/lib/ai/provider";
import { describeError, flashRedirect, type FlashMessage } from "@/lib/flash";

function isChronicleCategory(value: string): value is ChronicleCategory {
  return (CATEGORIES as readonly string[]).includes(value);
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ editionId: string; category: string }> },
) {
  const { editionId, category: rawCategory } = await params;
  const eId = Number(editionId);
  const category = decodeURIComponent(rawCategory);

  if (!isChronicleCategory(category)) {
    return new Response("Not found", { status: 404 });
  }

  const aiModel = await resolveAiModel();
  if (!aiModel) {
    return flashRedirect(request, `/admin/editions/${eId}/edit`, [
      { type: "error", text: AI_PROVIDER_NOT_CONFIGURED_MESSAGE },
    ]);
  }

  let message: FlashMessage;
  try {
    await regenerateChronicleSection(eId, category, aiModel);
    message = { type: "success", text: `"${category}" regenerated by AI.` };
  } catch (error) {
    message = { type: "error", text: `AI regeneration failed: ${describeError(error)}` };
  }

  return flashRedirect(request, `/admin/editions/${eId}/edit`, [message]);
}
