/**
 * Re-run AI generation for a single article — ported from
 * `admin.article_regenerate` (`app/routes/admin.py:482-509`). Both success and
 * failure redirect back to the article edit page, matching the original.
 */

import type { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { regenerateArticle } from "@/lib/generation";
import { describeError, flashRedirect, type FlashMessage } from "@/lib/flash";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ editionId: string; articleId: string }> },
) {
  const { editionId, articleId } = await params;
  const eId = Number(editionId);
  const aId = Number(articleId);

  const article = await prisma.article.findUnique({ where: { id: aId } });
  if (!article || article.editionId !== eId) {
    return new Response("Not found", { status: 404 });
  }

  if (!process.env.OPENAI_API_KEY) {
    return flashRedirect(request, `/admin/editions/${eId}/edit`, [
      { type: "error", text: "OPENAI_API_KEY not configured." },
    ]);
  }

  let message: FlashMessage;
  try {
    await regenerateArticle(aId);
    message = { type: "success", text: "Article regenerated by AI." };
  } catch (error) {
    message = { type: "error", text: `AI regeneration failed: ${describeError(error)}` };
  }

  return flashRedirect(request, `/admin/editions/${eId}/articles/${aId}/edit`, [message]);
}
